Repository d0mmi/Aniflix-App, pull requests merged in 2019-11, with the labels that each got.

#26 AA 68
  lib/api/APIManager.dart
  lib/api/objects/LoginResponse.dart
  lib/api/objects/RegisterResponse.dart
  lib/api/objects/Stream.dart
  lib/components/appbars/customappbar.dart
  lib/components/custom/text/highlighted_text_box.dart
  lib/components/navigationbars/mainbar.dart
  lib/components/screens/favoriten.dart
  lib/components/screens/home.dart
  lib/components/screens/login.dart
  lib/components/screens/profil.dart
  lib/components/screens/register.dart
  lib/components/screens/settings.dart
  lib/components/screens/verlauf.dart
  lib/components/screens/watchlist.dart
  lib/main.dart
  lib/themes/theme.dart
  lib/themes/themeManager.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#27 Aa 23
  lib/api/APIManager.dart
  lib/api/objects/CalendarDay.dart
  lib/api/objects/CalendarShow.dart
  lib/components/appbars/customappbar.dart
  lib/components/navigationbars/mainbar.dart
  lib/components/screens/calendar.dart
  lib/components/screens/home.dart
Labels: enhancement

#28 fixes
  lib/components/appbars/customappbar.dart
  lib/components/navigationbars/mainbar.dart
  lib/components/screens/login.dart
  lib/components/screens/register.dart
  lib/components/screens/settings.dart
  lib/main.dart
  lib/themes/themeManager.dart
Labels: bug

#29 Aa 72
  lib/components/appbars/customappbar.dart
Labels: enhancement

#30 Aa 70
  lib/components/screens/login.dart
  lib/components/screens/settings.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#31 Aa 53
  lib/api/APIManager.dart
  lib/api/objects/Airing.dart
  lib/api/objects/Anime.dart
  lib/api/objects/AnimeSeason.dart
  lib/api/objects/Episode.dart
  lib/api/objects/Genre.dart
  lib/api/objects/Group.dart
  lib/api/objects/Pivot.dart
  lib/api/objects/Season.dart
  lib/api/objects/Vote.dart
  lib/components/custom/text/highlighted_text_box.dart
  lib/components/navigationbars/mainbar.dart
  lib/components/screens/anime.dart
  lib/components/screens/home.dart
  lib/components/screens/login.dart
  lib/components/slider/SliderElement.dart
  lib/main.dart
Labels: enhancement

#33 AA-54 Create Stream-Select-Bar
  lib/components/screens/episode.dart
  lib/components/screens/settings.dart
Labels: enhancement

#35 Aa 51
  assets/images/ger.png
  assets/images/gerjap.png
  assets/images/jap.png
  lib/api/APIManager.dart
  lib/api/objects/AnimeSeason.dart
  lib/components/custom/slider/slider_with_headline.dart
  lib/components/screens/anime.dart
  lib/components/screens/settings.dart
  lib/main.dart
  lib/themes/themeManager.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#37 Aa 71
  android/app/build.gradle
  lib/api/APIManager.dart
  lib/api/objects/Stream.dart
  lib/api/objects/anime/Anime.dart
  lib/api/objects/anime/AnimeSeason.dart
  lib/api/objects/anime/Genre.dart
  lib/api/objects/anime/Vote.dart
  lib/api/objects/calendar/CalendarDay.dart
  lib/api/objects/calendar/CalendarShow.dart
  lib/api/objects/episode/Comment.dart
  lib/api/objects/episode/EpisodeInfo.dart
  lib/api/objects/news/News.dart
  lib/api/objects/subbox/SubEpisode.dart
  lib/components/screens/anime.dart
  lib/components/screens/calendar.dart
  lib/components/screens/episode.dart
  lib/components/screens/subbox.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#38 Hotfix
  lib/components/screens/episode.dart
Labels: bug

#39 AA-60 Create Sorted List
  lib/api/APIManager.dart
  lib/api/objects/Show.dart
  lib/api/objects/allanime/genrewithshow.dart
Labels: enhancement

#40 AA-74 Create News Page
  lib/components/appbars/customappbar.dart
  lib/components/screens/news.dart
Labels: enhancement

#41 AA-59 Create Filter
  lib/components/screens/animelist.dart
Labels: enhancement

#42 Add Genres to Anime Page
  lib/api/objects/anime/Anime.dart
  lib/components/custom/text/highlighted_text_box.dart
  lib/components/screens/anime.dart
  lib/components/slider/TextboxSliderElement.dart
  lib/components/slider/carousel/AnimeCarousel.dart
  lib/components/slider/carousel/TextBoxCarousel.dart
Labels: enhancement

#43 Aa 60
  lib/api/APIManager.dart
  lib/components/navigationbars/mainbar.dart
  lib/components/screens/animelist.dart
Labels: enhancement

#44 Aa 81
  docs/class_diagramm.puml
  docs/class_diagramm.svg
  lib/api/APIManager.dart
  lib/api/objects/anime/reviews/Review.dart
  lib/api/objects/anime/reviews/ReviewShow.dart
  lib/components/appbars/customappbar.dart
  lib/components/custom/comments/AnswerCommentComponent.dart
  lib/components/custom/comments/CommentComponent.dart
  lib/components/custom/comments/SubCommentContainer.dart
  lib/components/custom/comments/commentContainer.dart
  lib/components/screens/anime.dart
  lib/components/screens/animelist.dart
  lib/components/screens/episode.dart
Labels: enhancement

#45 AA-77 Create Watchlist
  lib/components/screens/settings.dart
  lib/components/screens/watchlist.dart
Labels: enhancement

#46 AA-79 Create Favorites
  lib/components/screens/favoriten.dart
  lib/components/screens/settings.dart
Labels: enhancement

#47 AA-78 Create Verlauf
  lib/api/APIManager.dart
  lib/api/objects/history/historyEpisode.dart
  lib/components/screens/settings.dart
  lib/components/screens/verlauf.dart
Labels: enhancement

#48 Aa 65
  lib/api/APIManager.dart
  lib/api/objects/anime/reviews/Review.dart
  lib/components/custom/comments/AnswerCommentComponent.dart
  lib/components/custom/comments/CommentComponent.dart
  lib/components/custom/comments/SubCommentContainer.dart
  lib/components/custom/comments/commentContainer.dart
  lib/components/custom/dialogs/ratingDialog.dart
  lib/components/custom/dialogs/writeReviewDialog.dart
  lib/components/custom/review/reviewElement.dart
  lib/components/screens/anime.dart
  lib/components/screens/review.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#49 Aa 56
  lib/api/APIManager.dart
  lib/components/custom/comments/AnswerCommentComponent.dart
  lib/components/custom/comments/CommentComponent.dart
  lib/components/custom/comments/commentContainer.dart
  lib/components/screens/episode.dart
Labels: enhancement

#50 Hotfix
  lib/api/APIManager.dart
  lib/components/screens/home.dart
  lib/components/slider/SliderElement.dart
Labels: enhancement

#51 Aa 83
  lib/api/APIManager.dart
  lib/components/appbars/customappbar.dart
  lib/components/custom/anime/animeDescription.dart
  lib/components/custom/anime/animeHeader.dart
  lib/components/custom/anime/episodeList.dart
  lib/components/custom/dialogs/logoutDialog.dart
  lib/components/custom/episode/animePlayer.dart
  lib/components/custom/episode/comments/AnswerCommentComponent.dart
  lib/components/custom/episode/comments/CommentComponent.dart
  lib/components/custom/episode/comments/SubCommentContainer.dart
  lib/components/custom/episode/comments/commentContainer.dart
  lib/components/custom/episode/comments/commentPanel.dart
  lib/components/custom/episode/episodeBar.dart
  lib/components/custom/episode/episodeHeader.dart
  lib/components/custom/images/aniflixImage.dart
  lib/components/custom/listelements/imageListElement.dart
  lib/components/custom/listelements/listElement.dart
  lib/components/custom/news/newsContainer.dart
  lib/components/custom/review/reviewElement.dart
  lib/components/custom/slider/slider_with_headline.dart
  lib/components/custom/text/theme_text.dart
  lib/components/navigationbars/mainbar.dart
  lib/components/screens/anime.dart
  lib/components/screens/animelist.dart
  lib/components/screens/calendar.dart
  lib/components/screens/episode.dart
  lib/components/screens/favoriten.dart
  lib/components/screens/login.dart
  lib/components/screens/news.dart
  lib/components/screens/profil.dart
  lib/components/screens/register.dart
  lib/components/screens/review.dart
  lib/components/screens/settings.dart
  lib/components/screens/subbox.dart
  lib/components/screens/verlauf.dart
  lib/components/screens/watchlist.dart
  lib/main.dart
  test/widget_test.dart
Labels: enhancement

#52 .
  docs/class_diagramm.drawio
  docs/class_diagramm.png
  docs/class_diagramm.puml
  docs/class_diagramm.svg
Labels: documentation

#53 Aa 84
  docs/Development_Diagram.drawio
  docs/Development_Diagram.png
  docs/SAD.md
  docs/UCD_1_2.png
  docs/UCD_1_22.png
  docs/UCD_1_23 (1).drawio
  docs/UCD_1_23.drawio
  docs/UCD_1_23.png
Labels: documentation
