Repository d0mmi/Aniflix-App, pull requests merged in 2020-07, with the labels that each got.

#97 add new Use Case Flow Charts
  docs/UC/Diagrams/activity_diagramm_ads.drawio
  docs/UC/Diagrams/activity_diagramm_ads.png
  docs/UC/Diagrams/activity_diagramm_userpage.drawio
  docs/UC/Diagrams/activity_diagramm_userpage.png
Labels: documentation

#100 Aa 146
  .flutter-plugins-dependencies
  lib/components/custom/dialogs/logoutDialog.dart
  lib/components/screens/login.dart
  lib/main.dart
Labels: bug

#104 Aa 154
  lib/api/APIManager.dart
  lib/api/objects/calendar/CalendarShow.dart
  lib/components/custom/episode/animePlayer.dart
  lib/components/custom/text/highlighted_text_box.dart
  lib/components/screens/calendar.dart
  lib/components/screens/login.dart
  lib/components/slider/SliderElement.dart
  lib/main.dart
Labels: bug, enhancement

#105 AA-147 Add Native Ads
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/components/screens/AppErrorScreen.dart
  lib/components/screens/anime.dart
  lib/components/screens/animelist.dart
  lib/components/screens/calendar.dart
  lib/components/screens/chat.dart
  lib/components/screens/episode.dart
  lib/components/screens/favoriten.dart
  lib/components/screens/home.dart
  lib/components/screens/news.dart
  lib/components/screens/profil.dart
  lib/components/screens/review.dart
  lib/components/screens/search.dart
  lib/components/screens/settings.dart
  lib/components/screens/subbox.dart
  lib/components/screens/userlist.dart
  lib/components/screens/verlauf.dart
  lib/components/screens/watchlist.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#106 Bugfixes
  .flutter-plugins-dependencies
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/xyz/dommy/aniflix_app/MainActivity.kt
  lib/components/custom/episode/animePlayer.dart
  lib/components/screens/episode.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#107 fixed
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/components/screens/anime.dart
  lib/components/screens/home.dart
  lib/main.dart
Labels: bug

#108 AA-160 Select prefered lang / hoster
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/api/objects/User.dart
  lib/components/custom/episode/episodeHeader.dart
  lib/components/screens/episode.dart
  test/widget_tests/customComponentsEpisode_test.dart
  test/widget_tests/customDialogs_test.dart
  test/widget_tests/customEpisodeComments_test.dart
Labels: enhancement

#109 Update README.md
  README.md
Labels: documentation

#111 Aa 130
  .flutter-plugins-dependencies
  lib/components/navigationbars/profilebar.dart
  lib/components/screens/profil.dart
  lib/main.dart
Labels: enhancement

#112 Aa 155
  .flutter-plugins-dependencies
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  lib/components/custom/episode/animePlayer.dart
  lib/components/screens/episode.dart
  lib/components/screens/home.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#113 AA-131 Push Notifications
  .flutter-plugins-dependencies
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#114 Aa 161
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/components/screens/AppErrorScreen.dart
  lib/components/screens/login.dart
  lib/components/screens/profil.dart
  lib/components/screens/register.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#115 AA-156 Implement Custom Background
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/components/appbars/customappbar.dart
  lib/components/custom/episode/comments/SubCommentContainer.dart
  lib/components/custom/episode/comments/commentContainer.dart
  lib/components/custom/listelements/listElement.dart
  lib/components/custom/slider/slider_with_headline.dart
  lib/components/screens/anime.dart
  lib/components/screens/animelist.dart
  lib/components/screens/calendar.dart
  lib/components/screens/chat.dart
  lib/components/screens/episode.dart
  lib/components/screens/favoriten.dart
  lib/components/screens/friendlist.dart
  lib/components/screens/home.dart
  lib/components/screens/news.dart
  lib/components/screens/profil.dart
  lib/components/screens/profileanimelist.dart
  lib/components/screens/profilesettings.dart
  lib/components/screens/profilesubbox.dart
  lib/components/screens/review.dart
  lib/components/screens/search.dart
  lib/components/screens/settings.dart
  lib/components/screens/subbox.dart
  lib/components/screens/userlist.dart
  lib/components/screens/verlauf.dart
  lib/components/screens/watchlist.dart
  lib/components/slider/SliderElement.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#116 AA-148 Change Avatar
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/components/screens/profil.dart
  lib/components/screens/profilesettings.dart
Labels: enhancement
