Repository d0mmi/Aniflix-App, pull requests merged in 2020-06, with the labels that each got.

#83 AA-141 Hoster Auswahl durch Werbung beeinträchtigt
  .flutter-plugins-dependencies
  lib/components/screens/episode.dart
Labels: bug

#84 AA-133 Fix Text Edges
  lib/api/APIManager.dart
  lib/components/custom/text/highlighted_text_box.dart
  lib/components/screens/calendar.dart
  lib/components/slider/SliderElement.dart
Labels: bug

#85 AA-132 Freundesliste in Eingehend und Ausgehend sortieren
  lib/components/screens/friendlist.dart
Labels: enhancement

#87 Aa 142
  docs/metrics/new/index.html
  docs/metrics/new/lib/components/screens/animelist.html
  docs/metrics/new/lib/components/screens/index.html
  lib/components/screens/animelist.dart
Labels: documentation, enhancement

#88 AA-140 Anzeige bei Suche wenn nix gefunden wurde
  .flutter-plugins-dependencies
  lib/components/custom/search/searchList.dart
  lib/components/screens/search.dart
  lib/components/screens/userlist.dart
Labels: enhancement

#89 Aa 143
  .flutter-plugins-dependencies
  .gitignore
  lib/components/custom/episode/animePlayer.dart
  lib/components/screens/episode.dart
  lib/main.dart
  lib/parser/FlexParser.dart
  lib/parser/GoUnlimitedParser.dart
  lib/parser/HosterParser.dart
  lib/parser/MixDropParser.dart
  lib/parser/StreamTapeParser.dart
  lib/parser/VivoParser.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#90 AA-144 Improve Slider
  .flutter-plugins-dependencies
  lib/components/custom/slider/slider_with_headline.dart
  lib/components/slider/SliderElement.dart
  lib/components/slider/carousel/AnimeCarousel.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#91 AA-126 Fix Avatar
  .flutter-plugins-dependencies
  lib/components/appbars/customappbar.dart
  lib/components/custom/episode/comments/AnswerCommentComponent.dart
  lib/components/custom/episode/comments/CommentComponent.dart
  lib/components/custom/episode/comments/SubCommentContainer.dart
  lib/components/custom/episode/comments/commentContainer.dart
  lib/components/custom/images/ProfileImage.dart
  lib/components/custom/listelements/iconListElement.dart
Labels: bug

#92 AA-138 Einem Freund empfehlen Funktion
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/components/custom/dialogs/ratingDialog.dart
  lib/components/screens/anime.dart
  pubspec.lock
Labels: enhancement

#94 AA-145 Write Tests
  .flutter-plugins-dependencies
  lib/components/custom/anime/animeHeader.dart
  lib/components/custom/anime/episodeList.dart
  lib/components/custom/episode/episodeBar.dart
  test/api_test.dart
  test/unit_tests/api_test.dart
  test/widget_tests/change_theme_test.dart
  test/widget_tests/customComponentsAnime_test.dart
  test/widget_tests/customComponentsChat_test.dart
  test/widget_tests/customComponentsEpisode_test.dart
  test/widget_tests/customDialogs_test.dart
  test/widget_tests/customEpisodeComments_test.dart
Labels: enhancement
