Repository d0mmi/Aniflix-App, pull requests merged in 2020-05, with the labels that each got.

#74 Aa 128 add Unit Tests
  .flutter-plugins-dependencies
  coverage/lcov.info
  lib/components/screens/settings.dart
  lib/main.dart
  pubspec.lock
  test/api_test.dart
  test/change_theme_test.dart
  test/widget_test.dart
Labels: enhancement

#75 AA-99 Add Master Test Plan
  docs/Master Test Plan.pdf
Labels: documentation

#77 Aa 122
  .flutter-plugins-dependencies
  lib/api/APIManager.dart
  lib/cache/cacheManager.dart
  lib/components/custom/episode/episodeHeader.dart
  lib/components/custom/listelements/iconListElement.dart
  lib/components/custom/text/highlighted_text_box.dart
  lib/components/custom/text/theme_text.dart
  lib/components/screens/favoriten.dart
  lib/components/screens/search.dart
  lib/components/screens/settings.dart
  lib/components/screens/userlist.dart
  lib/components/slider/SliderElement.dart
  lib/components/slider/TextboxSliderElement.dart
  lib/main.dart
  lib/themes/theme.dart
  lib/themes/themeManager.dart
  pubspec.lock
Labels: enhancement

#79 Aa 123
  lib/components/screens/profil.dart
Labels: enhancement

#80 Aa 124 personal notifications
  lib/api/APIManager.dart
  lib/api/objects/news/NotificationListData.dart
  lib/components/custom/news/notificationContainer.dart
  lib/components/screens/news.dart
  pubspec.lock
  test/api_test.dart
Labels: enhancement

#81 AA-134 Fix Text Color in Anime Season select
  lib/components/custom/anime/animeHeader.dart
  lib/components/custom/chat/chatComponent.dart
  lib/components/custom/chat/chatInput.dart
  lib/components/custom/dialogs/aboutMeDialog.dart
  lib/components/custom/dialogs/closeAppDialog.dart
  lib/components/custom/dialogs/reportDialog.dart
  lib/components/custom/dialogs/writeReviewDialog.dart
  lib/components/custom/episode/animePlayer.dart
  lib/components/custom/episode/comments/AnswerCommentComponent.dart
  lib/components/custom/episode/comments/CommentComponent.dart
  lib/components/custom/episode/comments/commentContainer.dart
  lib/components/custom/review/reviewElement.dart
  lib/components/screens/anime.dart
  lib/components/screens/animelist.dart
  lib/components/screens/register.dart
  lib/components/screens/review.dart
  lib/main.dart
Labels: bug

#82 AA-135 Refactoring
  .flutter-plugins-dependencies
  docs/Diagrams/designpattern/after.puml
  docs/Diagrams/designpattern/after.svg
  docs/Diagrams/designpattern/before.puml
  docs/Diagrams/designpattern/before.svg
  lib/components/custom/anime/animeDescription.dart
  lib/components/custom/anime/animeHeader.dart
  lib/components/custom/anime/episodeList.dart
  lib/components/custom/chat/chatComponent.dart
  lib/components/custom/chat/chatRulesDialog.dart
  lib/components/custom/dialogs/closeAppDialog.dart
  lib/components/custom/dialogs/logoutDialog.dart
  lib/components/custom/episode/comments/SubCommentContainer.dart
  lib/components/custom/episode/comments/commentContainer.dart
  lib/components/custom/episode/comments/commentList.dart
  lib/components/custom/episode/episodeBar.dart
  lib/components/custom/episode/episodeHeader.dart
  lib/components/custom/listelements/iconListElement.dart
  lib/components/custom/listelements/imageListElement.dart
  lib/components/custom/listelements/listElement.dart
  lib/components/custom/news/FriendNotification.dart
  lib/components/custom/news/NewsNotification.dart
  lib/components/custom/news/PersonalNotification.dart
  lib/components/custom/news/SubNotification.dart
  lib/components/custom/news/aniflix_notification.dart
  lib/components/custom/news/newsContainer.dart
  lib/components/custom/news/notificationContainer.dart
  lib/components/custom/rating/voteBar.dart
  lib/components/custom/review/reviewElement.dart
  lib/components/custom/search/searchList.dart
  lib/components/custom/slider/slider_with_headline.dart
  lib/components/custom/text/dateText.dart
  lib/components/custom/text/theme_text.dart
  lib/components/screens/anime.dart
  lib/components/screens/animelist.dart
  lib/components/screens/favoriten.dart
  lib/components/screens/friendlist.dart
  lib/components/screens/home.dart
  lib/components/screens/login.dart
  lib/components/screens/news.dart
  lib/components/screens/profil.dart
  lib/components/screens/profilesettings.dart
  lib/components/screens/profilesubbox.dart
  lib/components/screens/review.dart
  lib/components/screens/userlist.dart
  lib/components/screens/verlauf.dart
  lib/components/screens/watchlist.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement
